import type { Metadata } from "next";
import { profile } from "@/content/data/profile";
import { cvJsonLd, jsonLdScript } from "@/lib/jsonld";

export const metadata: Metadata = {
  title: "CV",
  description: `CV of ${profile.name} (${profile.handle}) - ${profile.role} @ ${profile.company}, Full Stack Developer & AI Engineer with ${profile.yearsExperience} years of experience. Laravel, Vue, React, LLM integrations. ${profile.location}.`,
  alternates: { canonical: "/cv" },
};

const PDF_HREF = "/Aditya-Kumar-CV.pdf";

/**
 * CV (SPEC S8): data-driven from profile.ts.
 * Screen + print = single linear column (ATS-safe: semantic HTML, standard section
 * names, no text-in-images). A separate two-column PDF lives at
 * public/Aditya-Kumar-CV.pdf (generated by scripts/build-cv-pdf.mjs).
 */
export default function CvPage() {
  return (
    <main className="mx-auto max-w-3xl flex-1 px-6 py-16">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLdScript(cvJsonLd()) }}
      />

      <header className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0">
          <h1 className="mono h2-rule text-4xl font-semibold">{profile.name}</h1>
          <p className="mt-2 text-lg" style={{ color: "var(--muted)" }}>
            {profile.headline}
          </p>
          <p className="mono mt-2 text-sm" style={{ color: "var(--muted)" }}>
            {profile.location}
            {profile.phone && (
              <>
                {" · "}
                <a href={`tel:${profile.phone.replace(/\s/g, "")}`}>{profile.phone}</a>
              </>
            )}{" "}
            · <a href={`mailto:${profile.email}`}>{profile.email}</a> ·{" "}
            <a href={profile.website}>adityadev.in</a> ·{" "}
            <a href={profile.github}>github.com/{profile.handle}</a> ·{" "}
            <a href={profile.linkedin}>linkedin.com/in/{profile.handle}</a>
          </p>
        </div>
        <a
          href={PDF_HREF}
          download
          data-no-print
          className="btn mono min-h-11 rounded border px-5 py-2.5 text-sm font-medium no-underline"
          style={{ borderColor: "var(--accent)", background: "var(--accent)", color: "var(--on-accent)" }}
        >
          Download PDF ↓
        </a>
      </header>

      <section className="mt-10">
        <h2 className="cv-section">Summary</h2>
        <p className="mt-4">
          {profile.role} at {profile.company} with {profile.yearsExperience} years of experience
          designing and shipping web products end to end - Laravel and PHP backends, Vue and React
          frontends, and production AI/LLM integrations. Lead architecture and delivery across a
          team of 10+ engineers, and have delivered 60+ client projects including payments,
          real-estate platforms, and AI-powered automation. Based in{" "}
          {profile.location.split(",")[0]}; working with clients worldwide.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="cv-section">Experience</h2>
        {profile.experience.map((e) => (
          <div key={e.company} className="mt-5">
            <h3 className="text-lg font-semibold">
              {e.role} - {e.company}
            </h3>
            <p className="mono text-sm" style={{ color: "var(--muted)" }}>
              {e.period}
              {"location" in e && e.location ? ` · ${e.location}` : ""}
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              {e.points.map((p) => (
                <li key={p}>{p}</li>
              ))}
            </ul>
          </div>
        ))}
      </section>

      <section className="mt-10">
        <h2 className="cv-section">Selected Projects</h2>
        <ul className="mt-4 space-y-3">
          {profile.projects.map((p) => (
            <li key={p.title}>
              <strong>{p.title}</strong> - {p.note}{" "}
              <span className="mono text-sm" style={{ color: "var(--muted)" }}>
                ({p.stack})
              </span>
            </li>
          ))}
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="cv-section">Skills</h2>
        <dl className="mt-4 space-y-3">
          {Object.entries(profile.skills).map(([group, items]) => (
            <div key={group} className="flex flex-col gap-1 sm:flex-row sm:gap-4">
              <dt className="mono w-40 shrink-0 text-sm font-medium" style={{ color: "var(--muted)" }}>
                {group}
              </dt>
              <dd>{items.join(" · ")}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="mt-10">
        <h2 className="cv-section">Education</h2>
        <ul className="mt-4 space-y-3">
          {profile.education.map((e) => (
            <li key={e.degree}>
              <span className="font-medium">{e.degree}</span> - {e.school}{" "}
              <span className="mono text-sm" style={{ color: "var(--muted)" }}>
                ({e.year} · {e.score})
              </span>
            </li>
          ))}
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="cv-section">Open Source</h2>
        <ul className="mt-4 space-y-3">
          {profile.openSource.map((o) => (
            <li key={o.title}>
              <strong>{o.title}</strong> - {o.note}
            </li>
          ))}
        </ul>
      </section>

      {profile.certifications.length > 0 && (
        <section className="mt-10">
          <h2 className="cv-section">Certifications</h2>
          <ul className="mt-4 space-y-2">
            {profile.certifications.map((c) => (
              <li key={c.name}>
                <span className="font-medium">{c.name}</span>
                <span style={{ color: "var(--muted)" }}>
                  {" "}
                  - {c.issuer}, {c.year}
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      <section className="mt-10">
        <h2 className="cv-section">Languages</h2>
        <p className="mt-4">
          {profile.languages.map((l, i) => (
            <span key={l.name}>
              {i > 0 && " · "}
              {l.name} <span style={{ color: "var(--muted)" }}>- {l.level}</span>
            </span>
          ))}
        </p>
      </section>
    </main>
  );
}
